In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
pd.options.display.max_columns = 30
df = pd.read_csv('../data/movies_metadata_cleaned.csv')

In [3]:
df.head()

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,director,production_companies,production_countries,belongs_to_collection,revenue,budget,vote_count,vote_average,popularity,status
0,862,Toy Story,No Tagline,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,John Lasseter,Pixar Animation Studios,United States of America,Toy Story Collection,373554033.0,30000000.0,5415.0,7.7,21.946943,Released
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,Joe Johnston,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,No Collection,262797249.0,65000000.0,2413.0,6.9,17.015539,Released
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,Howard Deutch,Warner Bros.|Lancaster Gate,United States of America,Grumpy Old Men Collection,0.0,0.0,92.0,6.5,11.712900,Released
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,Forest Whitaker,Twentieth Century Fox Film Corporation,United States of America,No Collection,81452156.0,16000000.0,34.0,6.1,3.859495,Released
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,Charles Shyer,Sandollar Productions|Touchstone Pictures,United States of America,Father of the Bride Collection,76578911.0,0.0,173.0,5.7,8.387519,Released

In [4]:
df.insert(16, 'profit/loss' , df['revenue'] - df['budget'])

In [5]:
df

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,director,production_companies,production_countries,belongs_to_collection,revenue,budget,profit/loss,vote_count,vote_average,popularity,status
0,862,Toy Story,No Tagline,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,John Lasseter,Pixar Animation Studios,United States of America,Toy Story Collection,373554033.0,30000000.0,343554033.0,5415.0,7.7,21.946943,Released
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,Joe Johnston,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,No Collection,262797249.0,65000000.0,197797249.0,2413.0,6.9,17.015539,Released
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,Howard Deutch,Warner Bros.|Lancaster Gate,United States of America,Grumpy Old Men Collection,0.0,0.0,0.0,92.0,6.5,11.712900,Released
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,Forest Whitaker,Twentieth Century Fox Film Corporation,United States of America,No Collection,81452156.0,16000000.0,65452156.0,34.0,6.1,3.859495,Released
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,Charles Shyer,Sandollar Productions|Touchstone Pictures,United States of America,Father of the Bride Collection,76578911.0,0.0,76578911.0,173.0,5.7,8.387519,Released
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45431,439050,Subdue,Rising and falling between a man and woman,Rising and falling between a man and woman.,1-01-01,90.0,Drama|Family,fa,فارسی,as Leila Hatami| as Kourosh Tahami| as Elham ...,Hamid Nematollah,NaN,Iran,No Collection,0.0,0.0,0.0,1.0,4.0,0.072051,Released
45432,111109,Century of Birthing,No Tagline,An artist struggles to finish his work while a...,2011-11-17,360.0,Drama,tl,NaN,Sister Angela as Angel Aquino|Homer as Perry D...,Lav Diaz,Sine Olivia,Philippines,No Collection,0.0,0.0,0.0,3.0,9.0,0.178241,Released
45433,67758,Betrayal,A deadly game of wits.,"When one of her hits goes wrong, a professiona...",2003-08-01,90.0,Action|Drama|Thriller,en,English,Emily Shaw as Erika Eleniak|Det. Mark Winston ...,Mark L. Lester,American World Pictures,United States of America,No Collection,0.0,0.0,0.0,6.0,3.8,0.903007,Released
45434,227506,Satan Triumphant,No Tagline,"In a small town live two brothers, one a minis...",1917-10-21,87.0,NaN,en,NaN,as Iwan Mosschuchin| as Nathalie Lissenko| as...,Yakov Protazanov,Yermoliev,Russia,No Collection,0.0,0.0,0.0,0.0,0.0,0.003503,Released
45435,461257,Queerama,No Tagline,50 years after decriminalisation of homosexual...,2017-06-09,75.0,NaN,en,English,NaN,Daisy Asquith,NaN,United Kingdom,No Collection,0.0,0.0,0.0,0.0,0.0,0.163015,Released

In [6]:
df.insert(17, 'roi' , df['profit/loss'] / df['budget'])

In [ ]:
df

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,director,production_companies,production_countries,belongs_to_collection,revenue,budget,profit/loss,roi,vote_count,vote_average,popularity,status
45431,439050,Subdue,Rising and falling between a man and woman,Rising and falling between a man and woman.,1-01-01,90.0,Drama|Family,fa,فارسی,as Leila Hatami| as Kourosh Tahami| as Elham ...,Hamid Nematollah,NaN,Iran,No Collection,0.0,0.0,0.0,NaN,1.0,4.0,0.072051,Released
45432,111109,Century of Birthing,No Tagline,An artist struggles to finish his work while a...,2011-11-17,360.0,Drama,tl,NaN,Sister Angela as Angel Aquino|Homer as Perry D...,Lav Diaz,Sine Olivia,Philippines,No Collection,0.0,0.0,0.0,NaN,3.0,9.0,0.178241,Released
45433,67758,Betrayal,A deadly game of wits.,"When one of her hits goes wrong, a professiona...",2003-08-01,90.0,Action|Drama|Thriller,en,English,Emily Shaw as Erika Eleniak|Det. Mark Winston ...,Mark L. Lester,American World Pictures,United States of America,No Collection,0.0,0.0,0.0,NaN,6.0,3.8,0.903007,Released
45434,227506,Satan Triumphant,No Tagline,"In a small town live two brothers, one a minis...",1917-10-21,87.0,NaN,en,NaN,as Iwan Mosschuchin| as Nathalie Lissenko| as...,Yakov Protazanov,Yermoliev,Russia,No Collection,0.0,0.0,0.0,NaN,0.0,0.0,0.003503,Released
45435,461257,Queerama,No Tagline,50 years after decriminalisation of homosexual...,2017-06-09,75.0,NaN,en,English,NaN,Daisy Asquith,NaN,United Kingdom,No Collection,0.0,0.0,0.0,NaN,0.0,0.0,0.163015,Released

In [11]:
df['was_hit'] = np.where(df['roi'] > 0, 'hit', 'flop')

In [12]:
df

,id,title,tagline,overview,release_date,runtime,genres,original_language,spoken_languages,cast,director,production_companies,production_countries,belongs_to_collection,revenue,budget,profit/loss,roi,vote_count,vote_average,popularity,status,was_hit
0,862,Toy Story,No Tagline,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,Animation|Comedy|Family,en,English,Woody (voice) as Tom Hanks|Buzz Lightyear (voi...,John Lasseter,Pixar Animation Studios,United States of America,Toy Story Collection,373554033.0,30000000.0,343554033.0,11.451801,5415.0,7.7,21.946943,Released,hit
1,8844,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,Adventure|Fantasy|Family,en,English|Français,Alan Parrish as Robin Williams|Samuel Alan Par...,Joe Johnston,TriStar Pictures|Teitler Film|Interscope Commu...,United States of America,No Collection,262797249.0,65000000.0,197797249.0,3.043035,2413.0,6.9,17.015539,Released,hit
2,15602,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,Romance|Comedy,en,English,Max Goldman as Walter Matthau|John Gustafson a...,Howard Deutch,Warner Bros.|Lancaster Gate,United States of America,Grumpy Old Men Collection,0.0,0.0,0.0,NaN,92.0,6.5,11.712900,Released,flop
3,31357,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,Comedy|Drama|Romance,en,English,Savannah 'Vannah' Jackson as Whitney Houston|B...,Forest Whitaker,Twentieth Century Fox Film Corporation,United States of America,No Collection,81452156.0,16000000.0,65452156.0,4.090760,34.0,6.1,3.859495,Released,hit
4,11862,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,1995-02-10,106.0,Comedy,en,English,George Banks as Steve Martin|Nina Banks as Dia...,Charles Shyer,Sandollar Productions|Touchstone Pictures,United States of America,Father of the Bride Collection,76578911.0,0.0,76578911.0,inf,173.0,5.7,8.387519,Released,hit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45431,439050,Subdue,Rising and falling between a man and woman,Rising and falling between a man and woman.,1-01-01,90.0,Drama|Family,fa,فارسی,as Leila Hatami| as Kourosh Tahami| as Elham ...,Hamid Nematollah,NaN,Iran,No Collection,0.0,0.0,0.0,NaN,1.0,4.0,0.072051,Released,flop
45432,111109,Century of Birthing,No Tagline,An artist struggles to finish his work while a...,2011-11-17,360.0,Drama,tl,NaN,Sister Angela as Angel Aquino|Homer as Perry D...,Lav Diaz,Sine Olivia,Philippines,No Collection,0.0,0.0,0.0,NaN,3.0,9.0,0.178241,Released,flop
45433,67758,Betrayal,A deadly game of wits.,"When one of her hits goes wrong, a professiona...",2003-08-01,90.0,Action|Drama|Thriller,en,English,Emily Shaw as Erika Eleniak|Det. Mark Winston ...,Mark L. Lester,American World Pictures,United States of America,No Collection,0.0,0.0,0.0,NaN,6.0,3.8,0.903007,Released,flop
45434,227506,Satan Triumphant,No Tagline,"In a small town live two brothers, one a minis...",1917-10-21,87.0,NaN,en,NaN,as Iwan Mosschuchin| as Nathalie Lissenko| as...,Yakov Protazanov,Yermoliev,Russia,No Collection,0.0,0.0,0.0,NaN,0.0,0.0,0.003503,Released,flop
45435,461257,Queerama,No Tagline,50 years after decriminalisation of homosexual...,2017-06-09,75.0,NaN,en,English,NaN,Daisy Asquith,NaN,United Kingdom,No Collection,0.0,0.0,0.0,NaN,0.0,0.0,0.163015,Released,flop