Importing necessary libriries

In [1]:
import pandas as pd 
import numpy as np 
import json
import ast

In [2]:
pd.options.display.max_columns = 30
df = pd.read_csv('../data/movies_metadata.csv')
df2 = pd.read_csv('../data/credits.csv')
df.head(10)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17448\1616237462.py:2: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,6.677277,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,5.23158,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,14.686036,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,"[{'name': 'United Artists', 'id': 60}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0

In [3]:
df2 = pd.read_csv('../data/credits.csv')
df.head(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",21.946943,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,17.015539,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,11.7129,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",3.859495,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,8.387519,/e64sOI48hQXyru7naBFyssKFxVd.jpg,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
5,False,NaN,60000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,949,tt0113277,en,Heat,"Obsessive master thief, Neil McCauley leads a ...",17.924927,/zMyfPUelumio3tiDKPffaUpsQTD.jpg,"[{'name': 'Regency Enterprises', 'id': 508}, {...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,False,7.7,1886.0
6,False,NaN,58000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,11860,tt0114319,en,Sabrina,An ugly duckling having undergone a remarkable...,6.677277,/jQh15y5YB7bWz1NtffNZmRw0s9D.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,False,6.2,141.0
7,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,45325,tt0112302,en,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,/sGO5Qa55p7wTu7FJcX4H4xIVKvS.jpg,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,False,5.4,45.0
8,False,NaN,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,9091,tt0114576,en,Sudden Death,International action superstar Jean Claude Van...,5.23158,/eoWvKD60lT95Ss1MYNgVExpo5iU.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,False,5.5,174.0
9,False,"{'id': 645, 'name': 'James Bond Collection', '...",58000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.mgm.com/view/movie/757/Goldeneye/,710,tt0113189,en,GoldenEye,James Bond must unmask the mysterious head of ...,14.686036,/5c0ovjT41KnYIHYuF4AWsTe3sKh.jpg,"[{'name': 'United Artists', 'id': 60}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,False,6.6,1194.0

Now we are going to find out whats really going inside our DataFrame of movies_metadata
it will help us to identify which type of data we have to really work with and we will perform operations accordingly

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.3+ MB

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  str
 1   crew    45476 non-null  str
 2   id      45476 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.0 MB

Firstly, we are going to remove duplicate rows from the dataset before merging to avoid anomalies while performing further operations

In [6]:
df[df.duplicated(subset=['id'], keep=False)].sort_values(by='id')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
676,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,105045,tt0111613,de,Das Versprechen,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1995-02-16,0.0,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,"A love, a hope, a wall.",The Promise,False,5.0,1.0
1465,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,105045,tt0111613,de,Das Versprechen,"East-Berlin, 1961, shortly after the erection ...",0.122178,/5WFIrBhOOgc0jGmoLxMZwWqCctO.jpg,"[{'name': 'Studio Babelsberg', 'id': 264}, {'n...","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",1995-02-16,0.0,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,"A love, a hope, a wall.",The Promise,False,5.0,1.0
44821,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,6.480376,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,"[{'name': 'TV Tokyo', 'id': 3034}, {'name': '4...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",2000-07-08,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,False,6.0,144.0
4114,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,10.264597,/5ILjS6XB5deiHop8SXPsYxXWVPE.jpg,"[{'name': 'TV Tokyo', 'id': 3034}, {'name': '4...","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",2000-07-08,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,False,6.0,143.0
5710,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,12.180836,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,"[{'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8...","[{'iso_3166_1': 'US', 'name': 'United States o...",1981-09-23,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous,False,4.9,7.0
20899,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,10.396878,/tOflyY8eUFWubLKJH7fKg4KwpCl.jpg,"[{'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8...","[{'iso_3166_1': 'US', 'name': 'United States o...",1981-09-23,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous,False,4.9,7.0
23534,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",0.110065,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,"[{'name': 'Canal+', 'id': 5358}, {'name': 'Art...","[{'iso_3166_1': 'FR', 'name': 'France'}]",2013-03-13,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915,False,7.0,20.0
4356,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",0.134014,/sGMPDg6je1zKi0TiX9b4pP6yN02.jpg,"[{'name': 'Canal+', 'id': 5358}, {'name': 'Art...","[{'iso_3166_1': 'FR', 'name': 'France'}]",2013-03-13,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915,False,7.0,20.0
24844,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.dealthemovie.com/,11115,tt0446676,en,Deal,As an ex-gambler teaches a hot-shot college ki...,6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,"[{'name': 'Andertainment Group', 'id': 2634}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2008-01-29,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Deal,False,5.2,22.0
14012,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.dealthemovie.com/,11115,tt0446676,en,Deal,As an ex-gambler teaches a hot-shot college ki...,6.880365,/kHaBqrrozaG7rj6GJg3sUCiM29B.jpg,"[{'name': 'Andertainment Group', 'id': 2634}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",2008-01-29,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Deal,False,5.2,22.0
21165,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,119916,tt0080000,en,The Tempest,"Prospero, the true Duke of Milan is now living...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,[],[],1980-02-27,0.0,123.0,[],Released,NaN,The Tempest,False,0.0,0.0
19890,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,119916,tt0080000,en,The Tempest,"Prospero, the true Duke of Milan is now living...",0.000018,/gLVRTxaLtUDkfscFKPyYrCtRnTk.jpg,[],[],1980-02-27,0.0,123.0,[],Released,NaN,The Tempest,False,0.0,0.0
5535,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",7.072301,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,[],"[{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...",2001-07-06,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,False,5.7,82.0
44826,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",6.080108,/bqL0PVHbQ8Jmw3Njcl38kW0CoeM.jpg,[],"[{'iso_3166_1': 'JP', 'name': 'Japan'}, {'iso_...",2001-07-06,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,False,5.7,82.0
11342,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",1.52896,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,"[{'name': 'Jafar Panahi Film Productions', 'id...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]",2006-05-26,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside,False,6.7,27.0
15765,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",1.529879,/nfkOkpudNNIjRrf0mTFVoiGzHyc.jpg,"[{'name': 'Jafar Panahi Film Productions', 'id...","[{'iso_3166_1': 'IR', 'name': 'Iran'}]",2006-05-26,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside,False,6.7,27.0
838,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",0.096079,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,"[{'name': 'Toho Company', 'id': 882}]","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",1953-04-29,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife,False,0.0,0.0
30001,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",0.619388,/z9WiHt5uQjs8L8tyBpRBKzlheF2.jpg,"[{'name': 'Toho Company', 'id': 882}]","[{'iso_3166_1': 'JP', 'name': 'Japan'}]",1953-04-29,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife,False,0.0,0.0
16764,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout,False,6.7,3.0
13261,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout,False,6.7,3.0
13375,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,0.411949,/8VSZ9coCzxOCW2wE2Qene1H1fKO.jpg,"[{'name': 'Filmiteollisuus Fine', 'id': 5166}]","[{'iso_3166_1': 'FI', 'name': 'Finland'}]",2008-12-26,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout,False,6.7,3.0
10419,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,3.185256,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,"[{'name': 'Magnolia Pictures', 'id': 1030}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2005-09-03,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble,False,6.4,36.0
12066,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,3.008299,/w56oo9nREcF54sNXVYuE9QxZFjT.jpg,"[{'name': 'Magnolia Pictures', 'id': 1030}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2005-09-03,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble,False,6.4,36.0
5130,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",5.373623,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",2002-03-17,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,False,4.9,89.0
33743,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",4.920175,/xGhDPrBz9mJN8CsIjA23jQSd3sc.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",2002-03-17,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,False,4.9,90.0
19925,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",NaN,152795,tt1821641,en,The Congress,More than two decades after catapulting to sta...,8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,"[{'name': 'Pandora Filmproduktion', 'id': 254}...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2013-05-16,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Congress,False,6.4,165.0
21854,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",NaN,152795,tt1821641,en,The Congress,More than two decades after catapulting to sta...,8.534039,/nnKX3ahYoT7P3au92dNgLf4pKwA.jpg,"[{'name': 'Pandora Filmproduktion', 'id': 254}...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",2013-05-16,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Congress,False,6.4,165.0
35798,False,"{'id': 158365, 'name': 'Why We Fight', 'poster...",0,"[{'id': 99, 'name': 'Documentary'}]",NaN,159849,tt0173769,en,Why We Fight: Divide and Conquer,"The third film of Frank Capra's 'Why We Fight""...",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1943-01-01,0.0,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Why We Fight: Divide and Conquer,False,5.0,1.0
13220,False,"{'id': 158365, 'name': 'Why We Fight', 'poster...",0,"[{'id': 99, 'name': 'Documentary'}]",NaN,159849,tt0173769,en,Why We Fight: Divide and Conquer,"The third film of Frank Capra's 'Why We Fight""...",0.473322,/g21ruZZ3BZeUDuKMb82kejjtufk.jpg,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",1943-01-01,0.0,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Why We Fight: Divide and Conquer,False,5.0,1.0
13603,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168538,tt0084387,en,Nana,"In Zola's Paris, an ingenue arrives at a tony ...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,"[{'name': 'Cannon Group', 'id': 1444}, {'name'...",[],1983-06-13,0.0,92.0,[],Released,NaN,"Nana, the True Key of Pleasure",False,4.7,3.0
28860,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168538,tt0084387,en,Nana,"In Zola's Paris, an ingenue arrives at a tony ...",1.276602,/pg4PUHRFrgNfACHSh5MITQ2gYch.jpg,"[{'name': 'Cannon Group', 'id': 1444}, {'name'...",[],1983-06-13,0.0,92.0,[],Released,NaN,"Nana, the True Key of Pleasure",False,4.7,3.0
22151,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",http://www.daysofdarknessthemovie.com/,18440,tt0499456,en,Days of Darkness,When a comet strikes Earth and kicks up a clou...,1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-01-01,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Days of Darkness,False,5.0,5.0
14000,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",http://www.daysofdarknessthemovie.com/,18440,tt0499456,en,Days of Darkness,When a comet strikes Earth and kicks up a clou...,1.436085,/tWCyKXHuSrQdLAvNeeVJBnhf1Yv.jpg,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",2007-01-01,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Days of Darkness,False,5.0,5.0
949,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,1.914697,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,"[{'name': 'Paramount Pictures', 'id': 4}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1932-12-08,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms,False,6.2,29.0
15074,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,2.411191,/k0MF0IIbJ2PfOIku2KyraXL72d8.jpg,"[{'name': 'Paramount Pictures', 'id': 4}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1932-12-08,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms,False,6.2,29.0
8068,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,23305,tt0295682,en,The Warrior,"In feudal India, a warrior (Khan) who renounce...",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,"[{'name': 'Filmfour', 'id': 6705}]","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2001-09-23,0.0,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,The Warrior,False,6.3,15.0
9327,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,23305,tt0295682,en,The Warrior,"In feudal India, a warrior (Khan) who renounce...",1.967992,/9GlrmbZO7VGyqhaSR1utinRJz3L.jpg,"[{'name': 'Filmfour', 'id': 6705}]","[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",2001-09-23,0.0,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,The Warrior,False,6.3,15.0
17229,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,25541,tt1327820,da,Broderskab,Former Danish servicemen Lars and Jimmy are th...,2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,[],"[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",2009-10-21,0.0,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,NaN,Brotherhood,False,7.1,21.0
23044,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,25541,tt1327820,da,Broderskab,Former Danish servicemen Lars and Jimmy are th...,2.587911,/q19Q5BRZpMXoNCA4OYodVozfjUh.jpg,[],"[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",2009-10-21,0.0,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,NaN,Brotherhood,False,7.1,21.0
24164,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,265189,tt2121382,sv,Turist,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,"[{'name': 'Motlys', 'id': 2783}, {'name': 'Cop...","[{'iso_3166_1': 'NO', 'name': 'Norway'}, {'iso...",2014-08-15,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,Force Majeure,False,6.8,255.0
45265,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,265189,tt2121382,sv,Turist,"While holidaying in the French Alps, a Swedish...",12.165685,/rGMtc9AtZsnWSSL5VnLaGvx1PI6.jpg,"[{'name': 'Motlys', 'id': 2783}, {'name': 'Cop...","[{'iso_3166_1': 'NO', 'name': 'Norway'}, {'iso...",2014-08-15,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,Force Majeure,False,6.8,255.0
33184,False,NaN,980000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,298721,tt2818654,th,รักที่ขอนแก่น,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"[{'name': 'Match Factory, The', 'id': 7306}, {...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-09-02,0.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Cemetery of Splendour,False,4.4,50.0
40040,False,NaN,980000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,298721,tt2818654,th,รักที่ขอนแก่น,"In a hospital, ten soldiers are being treated ...",2.535419,/5GasjPRAy5rlEyDOH7MeOyxyQGX.jpg,"[{'name': 'Match Factory, The', 'id': 7306}, {...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-09-02,0.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Cemetery of Splendour,False,4.4,50.0
15702,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,42495,tt0067306,en,King Lear,"King Lear, old and tired, divides his kingdom ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,"[{'name': 'Royal Shakespeare Company', 'id': 5...","[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",1971-02-04,0.0,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,NaN,King Lear,False,8.0,3.0
29374,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,42495,tt0067306,en,King Lear,"King Lear, old and tired, divides his kingdom ...",0.187901,/xuE1IlUCohbxMY0fiqKTT6d013n.jpg,"[{'name': 'Royal Shakespeare Company', 'id': 5...","[{'iso_3166_1': 'DK', 'name': 'Denmark'}, {'is...",1971-02-04,0.0,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,NaN,King Lear,False,8.0,3.0
33826,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",7.645827,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,"[{'name': 'Miramax Films', 'id': 14}, {'name':...","[{'iso_3166_1': 'US', 'name': 'United States o...",2002-12-30,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind,False,6.6,281.0
5865,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",11.331072,/o3Im9nPLAgtlw1j2LtpMebAotSe.jpg,"[{'name': 'Miramax Films', 'id': 14}, {'name':...","[{'iso_3166_1': 'US', 'name': 'United States o...",2002-12-30,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind,False,6.6,281.0

In [7]:
df = df.drop_duplicates(subset=['id'])

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45436 non-null  str
 1   belongs_to_collection  4491 non-null   str
 2   budget                 45436 non-null  str
 3   genres                 45436 non-null  str
 4   homepage               7777 non-null   str
 5   id                     45436 non-null  str
 6   imdb_id                45419 non-null  str
 7   original_language      45425 non-null  str
 8   original_title         45436 non-null  str
 9   overview               44482 non-null  str
 10  popularity             45431 non-null  object
 11  poster_path            45050 non-null  str
 12  production_companies   45433 non-null  str
 13  production_countries   45433 non-null  str
 14  release_date           45349 non-null  str
 15  revenue                45430 non-null  float64
 16  runtime                45173 non-null  float64
 17  spoken_languages       45430 non-null  str
 18  status                 45349 non-null  str
 19  tagline                20401 non-null  str
 20  title                  45430 non-null  str
 21  video                  45430 non-null  object
 22  vote_average           45430 non-null  float64
 23  vote_count             45430 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.7+ MB

In [9]:
df2[df2.duplicated(subset=['id'], keep=False)].sort_values(by='id')

,cast,crew,id
25950,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
25885,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
5865,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760b5', 'de...",4912
33838,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760a9', 'de...",4912
9165,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
...,...,...,...
25954,"[{'cast_id': 7, 'character': 'Hollander', 'cre...","[{'credit_id': '52fe4da29251416c9111ce5d', 'de...",199591
24163,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
45275,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
33196,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5448c8efc3a3680fb4001582', 'de...",298721
40051,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5739ceeac3a3683c9d000c12', 'de...",298721

In [10]:
df2 =df2.drop_duplicates(subset=['id'])

In [11]:
df2.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45432 non-null  str
 1   crew    45432 non-null  str
 2   id      45432 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.4 MB

We droped the duplicate rows but we cant merge it yet cause, in our initial dataframe column 'id' is considered as string while in df2 column 'id' is in int64 format ,

Now we are going to convert strings to int64, float64, datetime64[us], respectively

firstly, we are going to drop the unwanted rows

In [12]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

In [13]:
df = df.drop(columns=['adult', 'imdb_id','homepage','video','poster_path','original_title'])

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   str
 1   budget                 45436 non-null  str
 2   genres                 45436 non-null  str
 3   id                     45436 non-null  str
 4   original_language      45425 non-null  str
 5   overview               44482 non-null  str
 6   popularity             45431 non-null  object
 7   production_companies   45433 non-null  str
 8   production_countries   45433 non-null  str
 9   release_date           45349 non-null  str
 10  revenue                45430 non-null  float64
 11  runtime                45173 non-null  float64
 12  spoken_languages       45430 non-null  str
 13  status                 45349 non-null  str
 14  tagline                20401 non-null  str
 15  title                  45430 non-null  str
 16  vote_average           45430 non-null  float64
 17  vote_count             45430 non-null  float64
dtypes: float64(4), object(1), str(13)
memory usage: 6.6+ MB

In [15]:
df

,belongs_to_collection,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,5415.0
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,en,A family wedding reignites the ancient feud be...,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,en,Just when George Banks has recovered from his ...,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",439050,fa,Rising and falling between a man and woman.,0.072051,[],"[{'iso_3166_1': 'IR', 'name': 'Iran'}]",NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,4.0,1.0
45462,NaN,0,"[{'id': 18, 'name': 'Drama'}]",111109,tl,An artist struggles to finish his work while a...,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,3.0
45463,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,6.0
45464,NaN,0,[],227506,en,"In a small town live two brothers, one a minis...",0.003503,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,0.0
45465,NaN,0,[],461257,en,50 years after decriminalisation of homosexual...,0.163015,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,0.0

Here, as we can see columns belongs_to_collection, genres, production_companies, production_countries, spoken_languages are in json format we nedd to convert it into python object, for that we will use json and ast

In [16]:
df['belongs_to_collection'] = df['belongs_to_collection'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [17]:
df[['belongs_to_collection']].info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
dtypes: object(1)
memory usage: 709.9+ KB

As we can see column belongs_to_collection is successfully converted from string to object
Now, we are going to perform same operations on another columns

In [18]:
df['genres'] = df['genres'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [19]:
df['production_companies'] = df['production_companies'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [20]:
df['production_countries'] = df['production_countries'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [21]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [22]:
df[['belongs_to_collection','genres','production_companies','production_countries','spoken_languages']].info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   genres                 45436 non-null  object
 2   production_companies   45433 non-null  object
 3   production_countries   45433 non-null  object
 4   spoken_languages       45430 non-null  object
dtypes: object(5)
memory usage: 2.1+ MB

As we can see all the json's are converted to pythen objects successfully

Now we are going to covert release_date from string to datetime64[ns]

And budget to

In [23]:
df[['release_date']].info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   release_date  45349 non-null  str
dtypes: str(1)
memory usage: 709.9 KB

In [24]:
df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce')

In [25]:
df[['release_date']].info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   release_date  45346 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 709.9 KB

Now we are going to convert python objects like budget, popularity  to numeric values

In [26]:
df['budget'] = pd.to_numeric(df['budget'], errors = 'coerce')

In [27]:
df['popularity'] = pd.to_numeric(df['popularity'], errors = 'coerce')

In [28]:
df[['budget','popularity']].info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   budget      45433 non-null  float64
 1   popularity  45430 non-null  float64
dtypes: float64(2)
memory usage: 1.0 MB

Now, its time to convert release_date to datetime64[us]

In [29]:
df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce')

In [30]:
df['release_date'].info()

<class 'pandas.Series'>
Index: 45436 entries, 0 to 45465
Series name: release_date
Non-Null Count  Dtype
--------------  -----
45346 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 709.9 KB

In [31]:
df.info()

<class 'pandas.DataFrame'>
Index: 45436 entries, 0 to 45465
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4491 non-null   object
 1   budget                 45433 non-null  float64
 2   genres                 45436 non-null  object
 3   id                     45436 non-null  str
 4   original_language      45425 non-null  str
 5   overview               44482 non-null  str
 6   popularity             45430 non-null  float64
 7   production_companies   45433 non-null  object
 8   production_countries   45433 non-null  object
 9   release_date           45346 non-null  datetime64[us]
 10  revenue                45430 non-null  float64
 11  runtime                45173 non-null  float64
 12  spoken_languages       45430 non-null  object
 13  status                 45349 non-null  str
 14  tagline                20401 non-null  str
 15  title                  45430 non-null  str
 16  vote_average           45430 non-null  float64
 17  vote_count             45430 non-null  float64
dtypes: datetime64[us](1), float64(6), object(5), str(6)
memory usage: 6.6+ MB

As we can see all the strings are converted to there respective Dtype as it should

Now, its time for df2

In [32]:
df2.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45432 non-null  str
 1   crew    45432 non-null  str
 2   id      45432 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.4 MB

Again, Columns : cast and crew are in JSON format we need to convert into python objects

In [33]:
df2['cast'] = df2['cast'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [34]:
df2['crew'] = df2['crew'].apply(lambda x:ast.literal_eval(x) if isinstance(x, str)else np.nan)

In [35]:
df2[['cast','crew']].info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 45475
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45432 non-null  object
 1   crew    45432 non-null  object
dtypes: object(2)
memory usage: 1.0+ MB

Everything looks clear now in both the Dataframes

Now we are ready to fllater the lists of both the dataframes

In [36]:
df.loc[0, 'genres']

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [37]:
df['genres'] = df['genres'].apply(lambda x: "|".join(i['name'] for i in x))

In [38]:
df.loc[0, 'genres']

'Animation|Comedy|Family'

In [39]:
df.loc[0,'belongs_to_collection']

{'id': 10194,
 'name': 'Toy Story Collection',
 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg',
 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}

In [40]:
df['belongs_to_collection'] = df['belongs_to_collection'].apply(lambda x: x['name'] if isinstance(x, dict) else np.nan)

In [41]:
df.loc[0,'belongs_to_collection']

'Toy Story Collection'

In [42]:
df.loc[0,'spoken_languages']

[{'iso_639_1': 'en', 'name': 'English'}]

In [43]:
df['spoken_languages'] = df['spoken_languages'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [44]:
df.loc[0,'spoken_languages']

'English'

In [45]:
df.loc[0,'production_companies']

[{'name': 'Pixar Animation Studios', 'id': 3}]

In [46]:
df['production_companies'] = df['production_companies'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [47]:
df.loc[0,'production_companies']

'Pixar Animation Studios'

In [48]:
df.loc[0,'production_countries']

[{'iso_3166_1': 'US', 'name': 'United States of America'}]

In [49]:
df['production_countries'] = df['production_countries'].apply(lambda x: "|".join(i['name'] for i in x) if isinstance(x, list) else np.nan)

In [50]:
df.loc[0,'production_countries']

'United States of America'

We flattened the lists of dataframe1

Now, we will break df2 into 2 seperate columns cast and crew and perform further operations

In [51]:
df2.loc[0, 'cast']

[{'cast_id': 14,
  'character': 'Woody (voice)',
  'credit_id': '52fe4284c3a36847f8024f95',
  'gender': 2,
  'id': 31,
  'name': 'Tom Hanks',
  'order': 0,
  'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'},
 {'cast_id': 15,
  'character': 'Buzz Lightyear (voice)',
  'credit_id': '52fe4284c3a36847f8024f99',
  'gender': 2,
  'id': 12898,
  'name': 'Tim Allen',
  'order': 1,
  'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'},
 {'cast_id': 16,
  'character': 'Mr. Potato Head (voice)',
  'credit_id': '52fe4284c3a36847f8024f9d',
  'gender': 2,
  'id': 7167,
  'name': 'Don Rickles',
  'order': 2,
  'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'},
 {'cast_id': 17,
  'character': 'Slinky Dog (voice)',
  'credit_id': '52fe4284c3a36847f8024fa1',
  'gender': 2,
  'id': 12899,
  'name': 'Jim Varney',
  'order': 3,
  'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'},
 {'cast_id': 18,
  'character': 'Rex (voice)',
  'credit_id': '52fe4284c3a36847f8024fa5',
  'gender': 2,
  'id': 12900,
  'name': 'Wallace Shawn',
  'order': 4,
  'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'},
 {'cast_id': 19,
  'character': 'Hamm (voice)',
  'credit_id': '52fe4284c3a36847f8024fa9',
  'gender': 2,
  'id': 7907,
  'name': 'John Ratzenberger',
  'order': 5,
  'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'},
 {'cast_id': 20,
  'character': 'Bo Peep (voice)',
  'credit_id': '52fe4284c3a36847f8024fad',
  'gender': 1,
  'id': 8873,
  'name': 'Annie Potts',
  'order': 6,
  'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'},
 {'cast_id': 26,
  'character': 'Andy (voice)',
  'credit_id': '52fe4284c3a36847f8024fc1',
  'gender': 0,
  'id': 1116442,
  'name': 'John Morris',
  'order': 7,
  'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'},
 {'cast_id': 22,
  'character': 'Sid (voice)',
  'credit_id': '52fe4284c3a36847f8024fb1',
  'gender': 2,
  'id': 12901,
  'name': 'Erik von Detten',
  'order': 8,
  'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'},
 {'cast_id': 23,
  'character': 'Mrs. Davis (voice)',
  'credit_id': '52fe4284c3a36847f8024fb5',
  'gender': 1,
  'id': 12133,
  'name': 'Laurie Metcalf',
  'order': 9,
  'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'},
 {'cast_id': 24,
  'character': 'Sergeant (voice)',
  'credit_id': '52fe4284c3a36847f8024fb9',
  'gender': 2,
  'id': 8655,
  'name': 'R. Lee Ermey',
  'order': 10,
  'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'},
 {'cast_id': 25,
  'character': 'Hannah (voice)',
  'credit_id': '52fe4284c3a36847f8024fbd',
  'gender': 1,
  'id': 12903,
  'name': 'Sarah Freeman',
  'order': 11,
  'profile_path': None},
 {'cast_id': 27,
  'character': 'TV Announcer (voice)',
  'credit_id': '52fe4284c3a36847f8024fc5',
  'gender': 2,
  'id': 37221,
  'name': 'Penn Jillette',
  'order': 12,
  'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]

In [52]:
cast = pd.DataFrame(df2['cast'])
crew = pd.DataFrame(df2['crew'])

In [53]:
cast

                                                    cast
0      [{'cast_id': 14, 'character': 'Woody (voice)',...
1      [{'cast_id': 1, 'character': 'Alan Parrish', '...
2      [{'cast_id': 2, 'character': 'Max Goldman', 'c...
3      [{'cast_id': 1, 'character': 'Savannah 'Vannah...
4      [{'cast_id': 1, 'character': 'George Banks', '...
...                                                  ...
45471  [{'cast_id': 0, 'character': '', 'credit_id': ...
45472  [{'cast_id': 1002, 'character': 'Sister Angela...
45473  [{'cast_id': 6, 'character': 'Emily Shaw', 'cr...
45474  [{'cast_id': 2, 'character': '', 'credit_id': ...
45475                                                 []

[45432 rows x 1 columns]

In [54]:
cast['cast_info'] = cast['cast'].apply(lambda x: "|".join(f"{i['character']} as {i['name']}" for i in x) if isinstance(x, list) else np.nan)

In [55]:
cast_info = cast['cast_info']

In [56]:
cast_info.iloc[0]

'Woody (voice) as Tom Hanks|Buzz Lightyear (voice) as Tim Allen|Mr. Potato Head (voice) as Don Rickles|Slinky Dog (voice) as Jim Varney|Rex (voice) as Wallace Shawn|Hamm (voice) as John Ratzenberger|Bo Peep (voice) as Annie Potts|Andy (voice) as John Morris|Sid (voice) as Erik von Detten|Mrs. Davis (voice) as Laurie Metcalf|Sergeant (voice) as R. Lee Ermey|Hannah (voice) as Sarah Freeman|TV Announcer (voice) as Penn Jillette'

In [57]:
cast_info

0        Woody (voice) as Tom Hanks|Buzz Lightyear (voi...
1        Alan Parrish as Robin Williams|Samuel Alan Par...
2        Max Goldman as Walter Matthau|John Gustafson a...
3        Savannah 'Vannah' Jackson as Whitney Houston|B...
4        George Banks as Steve Martin|Nina Banks as Dia...
                               ...
45471     as Leila Hatami| as Kourosh Tahami| as Elham ...
45472    Sister Angela as Angel Aquino|Homer as Perry D...
45473    Emily Shaw as Erika Eleniak|Det. Mark Winston ...
45474     as Iwan Mosschuchin| as Nathalie Lissenko| as...
45475
Name: cast_info, Length: 45432, dtype: str

Here, we attached Character and Name columns it will help us to identify which character is played by which actor